services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/backend/media
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./genome_reference:/data/genome_reference
    environment:
      - GENOME_REFERENCE_ROOT=/data/genome_reference
    depends_on:
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend/media:/app/backend/media
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./genome_reference:/data/genome_reference
    environment:
      - GENOME_REFERENCE_ROOT=/data/genome_reference
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
